name: tag_release_version

on: [pull_request]
# on:
#   pull_request:
#     types:
#       - closed

jobs:
  tag_release_version:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Extract release name from git ref
      id: tag_name
      run: |
        BRANCH_NAME={{ github.pull_request.head.ref }}
        echo ::set-output name=BRANCH_NAME::${BRANCH_NAME}
